// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TestTaskDbContext))]
    [Migration("20260828122437_AddAuditoriumNavigationToReserves")]
    partial class AddAuditoriumNavigationToReserves
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Auditorium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseRentalPrice")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Auditoriums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BaseRentalPrice = 2000,
                            Capacity = 50,
                            Name = "Зал А"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BaseRentalPrice = 3500,
                            Capacity = 100,
                            Name = "Зал В"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BaseRentalPrice = 1500,
                            Capacity = 30,
                            Name = "Зал С"
                        });
                });

            modelBuilder.Entity("Domain.Entities.AuditoriumReserve", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditoriumId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("AuditoriumId");

                    b.ToTable("AuditoriumReserves");
                });

            modelBuilder.Entity("Domain.Entities.AuditoriumReserveService", b =>
                {
                    b.Property<Guid>("AuditoriumReserveId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditoriumServiceId")
                        .HasColumnType("uuid");

                    b.HasKey("AuditoriumReserveId", "AuditoriumServiceId");

                    b.HasIndex("AuditoriumServiceId");

                    b.ToTable("AuditoriumReserveServices");
                });

            modelBuilder.Entity("Domain.Entities.AuditoriumService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditoriumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("AuditoriumId", "ServiceId")
                        .IsUnique();

                    b.ToTable("AuditoriumServices");
                });

            modelBuilder.Entity("Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Проєктор",
                            Price = 500
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Wi-Fi",
                            Price = 300
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Звук",
                            Price = 700
                        });
                });

            modelBuilder.Entity("Domain.Entities.TimeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("TimeRates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            EndTime = new TimeOnly(17, 59, 59),
                            Rate = 1m,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            EndTime = new TimeOnly(22, 59, 59),
                            Rate = 0.8m,
                            StartTime = new TimeOnly(18, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            EndTime = new TimeOnly(8, 59, 59),
                            Rate = 0.9m,
                            StartTime = new TimeOnly(6, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            EndTime = new TimeOnly(13, 59, 59),
                            Rate = 1.15m,
                            StartTime = new TimeOnly(12, 0, 0)
                        });
                });

            modelBuilder.Entity("Domain.Entities.AuditoriumReserve", b =>
                {
                    b.HasOne("Domain.Entities.Auditorium", "Auditorium")
                        .WithMany("Reserves")
                        .HasForeignKey("AuditoriumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auditorium");
                });

            modelBuilder.Entity("Domain.Entities.AuditoriumReserveService", b =>
                {
                    b.HasOne("Domain.Entities.AuditoriumReserve", "AuditoriumReserve")
                        .WithMany("Services")
                        .HasForeignKey("AuditoriumReserveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AuditoriumService", "AuditoriumService")
                        .WithMany()
                        .HasForeignKey("AuditoriumServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditoriumReserve");

                    b.Navigation("AuditoriumService");
                });

            modelBuilder.Entity("Domain.Entities.AuditoriumService", b =>
                {
                    b.HasOne("Domain.Entities.Auditorium", "Auditorium")
                        .WithMany("AuditoriumServices")
                        .HasForeignKey("AuditoriumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auditorium");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Domain.Entities.Auditorium", b =>
                {
                    b.Navigation("AuditoriumServices");

                    b.Navigation("Reserves");
                });

            modelBuilder.Entity("Domain.Entities.AuditoriumReserve", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
